#= Even Fibonacci numbers Problem 2 Each new term in the Fibonacci sequence is
generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms. Answer: 4613732 =#


FourMillion = 4e6


function sumEvenFib(N)
	"Return sum of even-valued Fibonacci numbers below N"
	pair = [1, 1]
	fib = 0
	result = 0
	while fib <= N
		fib = pair[1] + pair[2]
		pair[1] = pair[2]
		pair[2] = fib
		if fib%2 == 0
			result += fib 
		end
	end
	println("Sum of the even-valued Fibonacci numbers\nbelow $N is $result.")
end

# sumEvenFib(FourMillion)