##Autogenerated module of /usr/include/sys/cdefs.h
module Cdefs
using Base, GetC

#Load library.

lib=dlopen("libcdefs")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.


end #module Cdefs
