##Autogenerated module of /usr/include/libnova/libnova.h
module Libnova
using Base, GetC

#Load library.

lib=dlopen("liblibnova")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.


end #module Libnova
