##Autogenerated module of /usr/include/SDL/SDL.h
module SDL
using Base, GetC

#Load library.

lib=dlopen("libSDL")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.


end #module SDL
