#Autogenerated, parameters: 

module Wordsize

#Autogenerated module of /usr/include/bits/wordsize.h
module Wordsize
using Base, GetC

#Load library.

lib=dlopen("libwordsize")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.


end #module Wordsize
