#Autogenerated, parameters: 

module Stubs-64

#Autogenerated module of /usr/include/gnu/stubs-64.h
module Stubs-64
using Base, GetC

#Load library.

lib=dlopen("libstubs-64")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.


end #module Stubs-64
