##Autogenerated module of /usr/include/inttypes.h
module Inttypes
using Base, GetC
using Stdint, Stdint

#Load library.

lib=dlopen("libinttypes")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.


end #module Inttypes
