##Autogenerated module of /usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.1/include/stddef.h
module Stddef
using Base, GetC

#Load library.

lib=dlopen("libstddef")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.

export ptrdiff_t
typealias ptrdiff_t Int64

export size_t
typealias size_t Uint64

export wchar_t
typealias wchar_t Int32


end #module Stddef
