#Autogenerated, parameters: 

module Features

#Autogenerated module of /usr/include/features.h
module Features
using Base, GetC

#Load library.

lib=dlopen("libfeatures")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.


end #module Features
