#Autogenerated, parameters: 

module Gl

#Autogenerated module of /usr/include/GL/gl.h
module Gl
using Base, GetC

#Load library.

lib=dlopen("libgl")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.

export GLenum
typealias GLenum Uint32

export GLboolean
typealias GLboolean Uint8

export GLbitfield
typealias GLbitfield Uint32

export GLvoid
typealias GLvoid Void

export GLbyte
typealias GLbyte Int8

export GLshort
typealias GLshort Int16

export GLint
typealias GLint Int32

export GLubyte
typealias GLubyte Uint8

export GLushort
typealias GLushort Uint16

export GLuint
typealias GLuint Uint32

export GLsizei
typealias GLsizei Int32

export GLfloat
typealias GLfloat Float32

export GLclampf
typealias GLclampf Float32

export GLdouble
typealias GLdouble Float64

export GLclampd
typealias GLclampd Float64

export glclearindex
@g glclearindex glClearIndex(c::GLfloat)::Void

export glclearcolor
@g glclearcolor glClearColor(red::GLclampf, green::GLclampf, blue::GLclampf, alpha::GLclampf)::Void

export glclear
@g glclear glClear(mask::GLbitfield)::Void

export glindexmask
@g glindexmask glIndexMask(mask::GLuint)::Void

export glcolormask
@g glcolormask glColorMask(red::GLboolean, green::GLboolean, blue::GLboolean, alpha::GLboolean)::Void

export glalphafunc
@g glalphafunc glAlphaFunc(func::GLenum, ref::GLclampf)::Void

export glblendfunc
@g glblendfunc glBlendFunc(sfactor::GLenum, dfactor::GLenum)::Void

export gllogicop
@g gllogicop glLogicOp(opcode::GLenum)::Void

export glcullface
@g glcullface glCullFace(mode::GLenum)::Void

export glfrontface
@g glfrontface glFrontFace(mode::GLenum)::Void

export glpointsize
@g glpointsize glPointSize(size::GLfloat)::Void

export gllinewidth
@g gllinewidth glLineWidth(width::GLfloat)::Void

export gllinestipple
@g gllinestipple glLineStipple(factor::GLint, pattern::GLushort)::Void

export glpolygonmode
@g glpolygonmode glPolygonMode(face::GLenum, mode::GLenum)::Void

export glpolygonoffset
@g glpolygonoffset glPolygonOffset(factor::GLfloat, units::GLfloat)::Void

export glpolygonstipple
@g glpolygonstipple glPolygonStipple(mask::Ptr{GLubyte})::Void

export glgetpolygonstipple
@g glgetpolygonstipple glGetPolygonStipple(mask::Ptr{GLubyte})::Void

export gledgeflag
@g gledgeflag glEdgeFlag(flag::GLboolean)::Void

export gledgeflagv
@g gledgeflagv glEdgeFlagv(flag::Ptr{GLboolean})::Void

export glscissor
@g glscissor glScissor(x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void

export glclipplane
@g glclipplane glClipPlane(plane::GLenum, equation::Ptr{GLdouble})::Void

export glgetclipplane
@g glgetclipplane glGetClipPlane(plane::GLenum, equation::Ptr{GLdouble})::Void

export gldrawbuffer
@g gldrawbuffer glDrawBuffer(mode::GLenum)::Void

export glreadbuffer
@g glreadbuffer glReadBuffer(mode::GLenum)::Void

export glenable
@g glenable glEnable(cap::GLenum)::Void

export gldisable
@g gldisable glDisable(cap::GLenum)::Void

export glisenabled
@g glisenabled glIsEnabled(cap::GLenum)::GLboolean

export glenableclientstate
@g glenableclientstate glEnableClientState(cap::GLenum)::Void

export gldisableclientstate
@g gldisableclientstate glDisableClientState(cap::GLenum)::Void

export glgetbooleanv
@g glgetbooleanv glGetBooleanv(pname::GLenum, params::Ptr{GLboolean})::Void

export glgetdoublev
@g glgetdoublev glGetDoublev(pname::GLenum, params::Ptr{GLdouble})::Void

export glgetfloatv
@g glgetfloatv glGetFloatv(pname::GLenum, params::Ptr{GLfloat})::Void

export glgetintegerv
@g glgetintegerv glGetIntegerv(pname::GLenum, params::Ptr{GLint})::Void

export glpushattrib
@g glpushattrib glPushAttrib(mask::GLbitfield)::Void

export glpopattrib
@g glpopattrib glPopAttrib()::Void

export glpushclientattrib
@g glpushclientattrib glPushClientAttrib(mask::GLbitfield)::Void

export glpopclientattrib
@g glpopclientattrib glPopClientAttrib()::Void

export glrendermode
@g glrendermode glRenderMode(mode::GLenum)::GLint

export glgeterror
@g glgeterror glGetError()::GLenum

export glgetstring
@g glgetstring glGetString(name::GLenum)::Ptr{GLubyte}

export glfinish
@g glfinish glFinish()::Void

export glflush
@g glflush glFlush()::Void

export glhint
@g glhint glHint(target::GLenum, mode::GLenum)::Void

export glcleardepth
@g glcleardepth glClearDepth(depth::GLclampd)::Void

export gldepthfunc
@g gldepthfunc glDepthFunc(func::GLenum)::Void

export gldepthmask
@g gldepthmask glDepthMask(flag::GLboolean)::Void

export gldepthrange
@g gldepthrange glDepthRange(near_val::GLclampd, far_val::GLclampd)::Void

export glclearaccum
@g glclearaccum glClearAccum(red::GLfloat, green::GLfloat, blue::GLfloat, alpha::GLfloat)::Void

export glaccum
@g glaccum glAccum(op::GLenum, value::GLfloat)::Void

export glmatrixmode
@g glmatrixmode glMatrixMode(mode::GLenum)::Void

export glortho
@g glortho glOrtho(left::GLdouble, right::GLdouble, bottom::GLdouble, top::GLdouble, near_val::GLdouble, far_val::GLdouble)::Void

export glfrustum
@g glfrustum glFrustum(left::GLdouble, right::GLdouble, bottom::GLdouble, top::GLdouble, near_val::GLdouble, far_val::GLdouble)::Void

export glviewport
@g glviewport glViewport(x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void

export glpushmatrix
@g glpushmatrix glPushMatrix()::Void

export glpopmatrix
@g glpopmatrix glPopMatrix()::Void

export glloadidentity
@g glloadidentity glLoadIdentity()::Void

export glloadmatrixd
@g glloadmatrixd glLoadMatrixd(m::Ptr{GLdouble})::Void

export glloadmatrixf
@g glloadmatrixf glLoadMatrixf(m::Ptr{GLfloat})::Void

export glmultmatrixd
@g glmultmatrixd glMultMatrixd(m::Ptr{GLdouble})::Void

export glmultmatrixf
@g glmultmatrixf glMultMatrixf(m::Ptr{GLfloat})::Void

export glrotated
@g glrotated glRotated(angle::GLdouble, x::GLdouble, y::GLdouble, z::GLdouble)::Void

export glrotatef
@g glrotatef glRotatef(angle::GLfloat, x::GLfloat, y::GLfloat, z::GLfloat)::Void

export glscaled
@g glscaled glScaled(x::GLdouble, y::GLdouble, z::GLdouble)::Void

export glscalef
@g glscalef glScalef(x::GLfloat, y::GLfloat, z::GLfloat)::Void

export gltranslated
@g gltranslated glTranslated(x::GLdouble, y::GLdouble, z::GLdouble)::Void

export gltranslatef
@g gltranslatef glTranslatef(x::GLfloat, y::GLfloat, z::GLfloat)::Void

export glislist
@g glislist glIsList(list::GLuint)::GLboolean

export gldeletelists
@g gldeletelists glDeleteLists(list::GLuint, range::GLsizei)::Void

export glgenlists
@g glgenlists glGenLists(range::GLsizei)::GLuint

export glnewlist
@g glnewlist glNewList(list::GLuint, mode::GLenum)::Void

export glendlist
@g glendlist glEndList()::Void

export glcalllist
@g glcalllist glCallList(list::GLuint)::Void

export glcalllists
@g glcalllists glCallLists(n::GLsizei, type::GLenum, lists::Ptr{GLvoid})::Void

export gllistbase
@g gllistbase glListBase(base::GLuint)::Void

export glbegin
@g glbegin glBegin(mode::GLenum)::Void

export glend
@g glend glEnd()::Void

export glvertex2d
@g glvertex2d glVertex2d(x::GLdouble, y::GLdouble)::Void

export glvertex2f
@g glvertex2f glVertex2f(x::GLfloat, y::GLfloat)::Void

export glvertex2i
@g glvertex2i glVertex2i(x::GLint, y::GLint)::Void

export glvertex2s
@g glvertex2s glVertex2s(x::GLshort, y::GLshort)::Void

export glvertex3d
@g glvertex3d glVertex3d(x::GLdouble, y::GLdouble, z::GLdouble)::Void

export glvertex3f
@g glvertex3f glVertex3f(x::GLfloat, y::GLfloat, z::GLfloat)::Void

export glvertex3i
@g glvertex3i glVertex3i(x::GLint, y::GLint, z::GLint)::Void

export glvertex3s
@g glvertex3s glVertex3s(x::GLshort, y::GLshort, z::GLshort)::Void

export glvertex4d
@g glvertex4d glVertex4d(x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void

export glvertex4f
@g glvertex4f glVertex4f(x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void

export glvertex4i
@g glvertex4i glVertex4i(x::GLint, y::GLint, z::GLint, w::GLint)::Void

export glvertex4s
@g glvertex4s glVertex4s(x::GLshort, y::GLshort, z::GLshort, w::GLshort)::Void

export glvertex2dv
@g glvertex2dv glVertex2dv(v::Ptr{GLdouble})::Void

export glvertex2fv
@g glvertex2fv glVertex2fv(v::Ptr{GLfloat})::Void

export glvertex2iv
@g glvertex2iv glVertex2iv(v::Ptr{GLint})::Void

export glvertex2sv
@g glvertex2sv glVertex2sv(v::Ptr{GLshort})::Void

export glvertex3dv
@g glvertex3dv glVertex3dv(v::Ptr{GLdouble})::Void

export glvertex3fv
@g glvertex3fv glVertex3fv(v::Ptr{GLfloat})::Void

export glvertex3iv
@g glvertex3iv glVertex3iv(v::Ptr{GLint})::Void

export glvertex3sv
@g glvertex3sv glVertex3sv(v::Ptr{GLshort})::Void

export glvertex4dv
@g glvertex4dv glVertex4dv(v::Ptr{GLdouble})::Void

export glvertex4fv
@g glvertex4fv glVertex4fv(v::Ptr{GLfloat})::Void

export glvertex4iv
@g glvertex4iv glVertex4iv(v::Ptr{GLint})::Void

export glvertex4sv
@g glvertex4sv glVertex4sv(v::Ptr{GLshort})::Void

export glnormal3b
@g glnormal3b glNormal3b(nx::GLbyte, ny::GLbyte, nz::GLbyte)::Void

export glnormal3d
@g glnormal3d glNormal3d(nx::GLdouble, ny::GLdouble, nz::GLdouble)::Void

export glnormal3f
@g glnormal3f glNormal3f(nx::GLfloat, ny::GLfloat, nz::GLfloat)::Void

export glnormal3i
@g glnormal3i glNormal3i(nx::GLint, ny::GLint, nz::GLint)::Void

export glnormal3s
@g glnormal3s glNormal3s(nx::GLshort, ny::GLshort, nz::GLshort)::Void

export glnormal3bv
@g glnormal3bv glNormal3bv(v::Ptr{GLbyte})::Void

export glnormal3dv
@g glnormal3dv glNormal3dv(v::Ptr{GLdouble})::Void

export glnormal3fv
@g glnormal3fv glNormal3fv(v::Ptr{GLfloat})::Void

export glnormal3iv
@g glnormal3iv glNormal3iv(v::Ptr{GLint})::Void

export glnormal3sv
@g glnormal3sv glNormal3sv(v::Ptr{GLshort})::Void

export glindexd
@g glindexd glIndexd(c::GLdouble)::Void

export glindexf
@g glindexf glIndexf(c::GLfloat)::Void

export glindexi
@g glindexi glIndexi(c::GLint)::Void

export glindexs
@g glindexs glIndexs(c::GLshort)::Void

export glindexub
@g glindexub glIndexub(c::GLubyte)::Void

export glindexdv
@g glindexdv glIndexdv(c::Ptr{GLdouble})::Void

export glindexfv
@g glindexfv glIndexfv(c::Ptr{GLfloat})::Void

export glindexiv
@g glindexiv glIndexiv(c::Ptr{GLint})::Void

export glindexsv
@g glindexsv glIndexsv(c::Ptr{GLshort})::Void

export glindexubv
@g glindexubv glIndexubv(c::Ptr{GLubyte})::Void

export glcolor3b
@g glcolor3b glColor3b(red::GLbyte, green::GLbyte, blue::GLbyte)::Void

export glcolor3d
@g glcolor3d glColor3d(red::GLdouble, green::GLdouble, blue::GLdouble)::Void

export glcolor3f
@g glcolor3f glColor3f(red::GLfloat, green::GLfloat, blue::GLfloat)::Void

export glcolor3i
@g glcolor3i glColor3i(red::GLint, green::GLint, blue::GLint)::Void

export glcolor3s
@g glcolor3s glColor3s(red::GLshort, green::GLshort, blue::GLshort)::Void

export glcolor3ub
@g glcolor3ub glColor3ub(red::GLubyte, green::GLubyte, blue::GLubyte)::Void

export glcolor3ui
@g glcolor3ui glColor3ui(red::GLuint, green::GLuint, blue::GLuint)::Void

export glcolor3us
@g glcolor3us glColor3us(red::GLushort, green::GLushort, blue::GLushort)::Void

export glcolor4b
@g glcolor4b glColor4b(red::GLbyte, green::GLbyte, blue::GLbyte, alpha::GLbyte)::Void

export glcolor4d
@g glcolor4d glColor4d(red::GLdouble, green::GLdouble, blue::GLdouble, alpha::GLdouble)::Void

export glcolor4f
@g glcolor4f glColor4f(red::GLfloat, green::GLfloat, blue::GLfloat, alpha::GLfloat)::Void

export glcolor4i
@g glcolor4i glColor4i(red::GLint, green::GLint, blue::GLint, alpha::GLint)::Void

export glcolor4s
@g glcolor4s glColor4s(red::GLshort, green::GLshort, blue::GLshort, alpha::GLshort)::Void

export glcolor4ub
@g glcolor4ub glColor4ub(red::GLubyte, green::GLubyte, blue::GLubyte, alpha::GLubyte)::Void

export glcolor4ui
@g glcolor4ui glColor4ui(red::GLuint, green::GLuint, blue::GLuint, alpha::GLuint)::Void

export glcolor4us
@g glcolor4us glColor4us(red::GLushort, green::GLushort, blue::GLushort, alpha::GLushort)::Void

export glcolor3bv
@g glcolor3bv glColor3bv(v::Ptr{GLbyte})::Void

export glcolor3dv
@g glcolor3dv glColor3dv(v::Ptr{GLdouble})::Void

export glcolor3fv
@g glcolor3fv glColor3fv(v::Ptr{GLfloat})::Void

export glcolor3iv
@g glcolor3iv glColor3iv(v::Ptr{GLint})::Void

export glcolor3sv
@g glcolor3sv glColor3sv(v::Ptr{GLshort})::Void

export glcolor3ubv
@g glcolor3ubv glColor3ubv(v::Ptr{GLubyte})::Void

export glcolor3uiv
@g glcolor3uiv glColor3uiv(v::Ptr{GLuint})::Void

export glcolor3usv
@g glcolor3usv glColor3usv(v::Ptr{GLushort})::Void

export glcolor4bv
@g glcolor4bv glColor4bv(v::Ptr{GLbyte})::Void

export glcolor4dv
@g glcolor4dv glColor4dv(v::Ptr{GLdouble})::Void

export glcolor4fv
@g glcolor4fv glColor4fv(v::Ptr{GLfloat})::Void

export glcolor4iv
@g glcolor4iv glColor4iv(v::Ptr{GLint})::Void

export glcolor4sv
@g glcolor4sv glColor4sv(v::Ptr{GLshort})::Void

export glcolor4ubv
@g glcolor4ubv glColor4ubv(v::Ptr{GLubyte})::Void

export glcolor4uiv
@g glcolor4uiv glColor4uiv(v::Ptr{GLuint})::Void

export glcolor4usv
@g glcolor4usv glColor4usv(v::Ptr{GLushort})::Void

export gltexcoord1d
@g gltexcoord1d glTexCoord1d(s::GLdouble)::Void

export gltexcoord1f
@g gltexcoord1f glTexCoord1f(s::GLfloat)::Void

export gltexcoord1i
@g gltexcoord1i glTexCoord1i(s::GLint)::Void

export gltexcoord1s
@g gltexcoord1s glTexCoord1s(s::GLshort)::Void

export gltexcoord2d
@g gltexcoord2d glTexCoord2d(s::GLdouble, t::GLdouble)::Void

export gltexcoord2f
@g gltexcoord2f glTexCoord2f(s::GLfloat, t::GLfloat)::Void

export gltexcoord2i
@g gltexcoord2i glTexCoord2i(s::GLint, t::GLint)::Void

export gltexcoord2s
@g gltexcoord2s glTexCoord2s(s::GLshort, t::GLshort)::Void

export gltexcoord3d
@g gltexcoord3d glTexCoord3d(s::GLdouble, t::GLdouble, r::GLdouble)::Void

export gltexcoord3f
@g gltexcoord3f glTexCoord3f(s::GLfloat, t::GLfloat, r::GLfloat)::Void

export gltexcoord3i
@g gltexcoord3i glTexCoord3i(s::GLint, t::GLint, r::GLint)::Void

export gltexcoord3s
@g gltexcoord3s glTexCoord3s(s::GLshort, t::GLshort, r::GLshort)::Void

export gltexcoord4d
@g gltexcoord4d glTexCoord4d(s::GLdouble, t::GLdouble, r::GLdouble, q::GLdouble)::Void

export gltexcoord4f
@g gltexcoord4f glTexCoord4f(s::GLfloat, t::GLfloat, r::GLfloat, q::GLfloat)::Void

export gltexcoord4i
@g gltexcoord4i glTexCoord4i(s::GLint, t::GLint, r::GLint, q::GLint)::Void

export gltexcoord4s
@g gltexcoord4s glTexCoord4s(s::GLshort, t::GLshort, r::GLshort, q::GLshort)::Void

export gltexcoord1dv
@g gltexcoord1dv glTexCoord1dv(v::Ptr{GLdouble})::Void

export gltexcoord1fv
@g gltexcoord1fv glTexCoord1fv(v::Ptr{GLfloat})::Void

export gltexcoord1iv
@g gltexcoord1iv glTexCoord1iv(v::Ptr{GLint})::Void

export gltexcoord1sv
@g gltexcoord1sv glTexCoord1sv(v::Ptr{GLshort})::Void

export gltexcoord2dv
@g gltexcoord2dv glTexCoord2dv(v::Ptr{GLdouble})::Void

export gltexcoord2fv
@g gltexcoord2fv glTexCoord2fv(v::Ptr{GLfloat})::Void

export gltexcoord2iv
@g gltexcoord2iv glTexCoord2iv(v::Ptr{GLint})::Void

export gltexcoord2sv
@g gltexcoord2sv glTexCoord2sv(v::Ptr{GLshort})::Void

export gltexcoord3dv
@g gltexcoord3dv glTexCoord3dv(v::Ptr{GLdouble})::Void

export gltexcoord3fv
@g gltexcoord3fv glTexCoord3fv(v::Ptr{GLfloat})::Void

export gltexcoord3iv
@g gltexcoord3iv glTexCoord3iv(v::Ptr{GLint})::Void

export gltexcoord3sv
@g gltexcoord3sv glTexCoord3sv(v::Ptr{GLshort})::Void

export gltexcoord4dv
@g gltexcoord4dv glTexCoord4dv(v::Ptr{GLdouble})::Void

export gltexcoord4fv
@g gltexcoord4fv glTexCoord4fv(v::Ptr{GLfloat})::Void

export gltexcoord4iv
@g gltexcoord4iv glTexCoord4iv(v::Ptr{GLint})::Void

export gltexcoord4sv
@g gltexcoord4sv glTexCoord4sv(v::Ptr{GLshort})::Void

export glrasterpos2d
@g glrasterpos2d glRasterPos2d(x::GLdouble, y::GLdouble)::Void

export glrasterpos2f
@g glrasterpos2f glRasterPos2f(x::GLfloat, y::GLfloat)::Void

export glrasterpos2i
@g glrasterpos2i glRasterPos2i(x::GLint, y::GLint)::Void

export glrasterpos2s
@g glrasterpos2s glRasterPos2s(x::GLshort, y::GLshort)::Void

export glrasterpos3d
@g glrasterpos3d glRasterPos3d(x::GLdouble, y::GLdouble, z::GLdouble)::Void

export glrasterpos3f
@g glrasterpos3f glRasterPos3f(x::GLfloat, y::GLfloat, z::GLfloat)::Void

export glrasterpos3i
@g glrasterpos3i glRasterPos3i(x::GLint, y::GLint, z::GLint)::Void

export glrasterpos3s
@g glrasterpos3s glRasterPos3s(x::GLshort, y::GLshort, z::GLshort)::Void

export glrasterpos4d
@g glrasterpos4d glRasterPos4d(x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void

export glrasterpos4f
@g glrasterpos4f glRasterPos4f(x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void

export glrasterpos4i
@g glrasterpos4i glRasterPos4i(x::GLint, y::GLint, z::GLint, w::GLint)::Void

export glrasterpos4s
@g glrasterpos4s glRasterPos4s(x::GLshort, y::GLshort, z::GLshort, w::GLshort)::Void

export glrasterpos2dv
@g glrasterpos2dv glRasterPos2dv(v::Ptr{GLdouble})::Void

export glrasterpos2fv
@g glrasterpos2fv glRasterPos2fv(v::Ptr{GLfloat})::Void

export glrasterpos2iv
@g glrasterpos2iv glRasterPos2iv(v::Ptr{GLint})::Void

export glrasterpos2sv
@g glrasterpos2sv glRasterPos2sv(v::Ptr{GLshort})::Void

export glrasterpos3dv
@g glrasterpos3dv glRasterPos3dv(v::Ptr{GLdouble})::Void

export glrasterpos3fv
@g glrasterpos3fv glRasterPos3fv(v::Ptr{GLfloat})::Void

export glrasterpos3iv
@g glrasterpos3iv glRasterPos3iv(v::Ptr{GLint})::Void

export glrasterpos3sv
@g glrasterpos3sv glRasterPos3sv(v::Ptr{GLshort})::Void

export glrasterpos4dv
@g glrasterpos4dv glRasterPos4dv(v::Ptr{GLdouble})::Void

export glrasterpos4fv
@g glrasterpos4fv glRasterPos4fv(v::Ptr{GLfloat})::Void

export glrasterpos4iv
@g glrasterpos4iv glRasterPos4iv(v::Ptr{GLint})::Void

export glrasterpos4sv
@g glrasterpos4sv glRasterPos4sv(v::Ptr{GLshort})::Void

export glrectd
@g glrectd glRectd(x1::GLdouble, y1::GLdouble, x2::GLdouble, y2::GLdouble)::Void

export glrectf
@g glrectf glRectf(x1::GLfloat, y1::GLfloat, x2::GLfloat, y2::GLfloat)::Void

export glrecti
@g glrecti glRecti(x1::GLint, y1::GLint, x2::GLint, y2::GLint)::Void

export glrects
@g glrects glRects(x1::GLshort, y1::GLshort, x2::GLshort, y2::GLshort)::Void

export glrectdv
@g glrectdv glRectdv(v1::Ptr{GLdouble}, v2::Ptr{GLdouble})::Void

export glrectfv
@g glrectfv glRectfv(v1::Ptr{GLfloat}, v2::Ptr{GLfloat})::Void

export glrectiv
@g glrectiv glRectiv(v1::Ptr{GLint}, v2::Ptr{GLint})::Void

export glrectsv
@g glrectsv glRectsv(v1::Ptr{GLshort}, v2::Ptr{GLshort})::Void

export glvertexpointer
@g glvertexpointer glVertexPointer(size::GLint, type::GLenum, stride::GLsizei, ptr::Ptr{GLvoid})::Void

export glnormalpointer
@g glnormalpointer glNormalPointer(type::GLenum, stride::GLsizei, ptr::Ptr{GLvoid})::Void

export glcolorpointer
@g glcolorpointer glColorPointer(size::GLint, type::GLenum, stride::GLsizei, ptr::Ptr{GLvoid})::Void

export glindexpointer
@g glindexpointer glIndexPointer(type::GLenum, stride::GLsizei, ptr::Ptr{GLvoid})::Void

export gltexcoordpointer
@g gltexcoordpointer glTexCoordPointer(size::GLint, type::GLenum, stride::GLsizei, ptr::Ptr{GLvoid})::Void

export gledgeflagpointer
@g gledgeflagpointer glEdgeFlagPointer(stride::GLsizei, ptr::Ptr{GLvoid})::Void

export glgetpointerv
@g glgetpointerv glGetPointerv(pname::GLenum, params::Ptr{Ptr{GLvoid}})::Void

export glarrayelement
@g glarrayelement glArrayElement(i::GLint)::Void

export gldrawarrays
@g gldrawarrays glDrawArrays(mode::GLenum, first::GLint, count::GLsizei)::Void

export gldrawelements
@g gldrawelements glDrawElements(mode::GLenum, count::GLsizei, type::GLenum, indices::Ptr{GLvoid})::Void

export glinterleavedarrays
@g glinterleavedarrays glInterleavedArrays(format::GLenum, stride::GLsizei, pointer::Ptr{GLvoid})::Void

export glshademodel
@g glshademodel glShadeModel(mode::GLenum)::Void

export gllightf
@g gllightf glLightf(light::GLenum, pname::GLenum, param::GLfloat)::Void

export gllighti
@g gllighti glLighti(light::GLenum, pname::GLenum, param::GLint)::Void

export gllightfv
@g gllightfv glLightfv(light::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export gllightiv
@g gllightiv glLightiv(light::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glgetlightfv
@g glgetlightfv glGetLightfv(light::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgetlightiv
@g glgetlightiv glGetLightiv(light::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export gllightmodelf
@g gllightmodelf glLightModelf(pname::GLenum, param::GLfloat)::Void

export gllightmodeli
@g gllightmodeli glLightModeli(pname::GLenum, param::GLint)::Void

export gllightmodelfv
@g gllightmodelfv glLightModelfv(pname::GLenum, params::Ptr{GLfloat})::Void

export gllightmodeliv
@g gllightmodeliv glLightModeliv(pname::GLenum, params::Ptr{GLint})::Void

export glmaterialf
@g glmaterialf glMaterialf(face::GLenum, pname::GLenum, param::GLfloat)::Void

export glmateriali
@g glmateriali glMateriali(face::GLenum, pname::GLenum, param::GLint)::Void

export glmaterialfv
@g glmaterialfv glMaterialfv(face::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glmaterialiv
@g glmaterialiv glMaterialiv(face::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glgetmaterialfv
@g glgetmaterialfv glGetMaterialfv(face::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgetmaterialiv
@g glgetmaterialiv glGetMaterialiv(face::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glcolormaterial
@g glcolormaterial glColorMaterial(face::GLenum, mode::GLenum)::Void

export glpixelzoom
@g glpixelzoom glPixelZoom(xfactor::GLfloat, yfactor::GLfloat)::Void

export glpixelstoref
@g glpixelstoref glPixelStoref(pname::GLenum, param::GLfloat)::Void

export glpixelstorei
@g glpixelstorei glPixelStorei(pname::GLenum, param::GLint)::Void

export glpixeltransferf
@g glpixeltransferf glPixelTransferf(pname::GLenum, param::GLfloat)::Void

export glpixeltransferi
@g glpixeltransferi glPixelTransferi(pname::GLenum, param::GLint)::Void

export glpixelmapfv
@g glpixelmapfv glPixelMapfv(map::GLenum, mapsize::GLsizei, values::Ptr{GLfloat})::Void

export glpixelmapuiv
@g glpixelmapuiv glPixelMapuiv(map::GLenum, mapsize::GLsizei, values::Ptr{GLuint})::Void

export glpixelmapusv
@g glpixelmapusv glPixelMapusv(map::GLenum, mapsize::GLsizei, values::Ptr{GLushort})::Void

export glgetpixelmapfv
@g glgetpixelmapfv glGetPixelMapfv(map::GLenum, values::Ptr{GLfloat})::Void

export glgetpixelmapuiv
@g glgetpixelmapuiv glGetPixelMapuiv(map::GLenum, values::Ptr{GLuint})::Void

export glgetpixelmapusv
@g glgetpixelmapusv glGetPixelMapusv(map::GLenum, values::Ptr{GLushort})::Void

export glbitmap
@g glbitmap glBitmap(width::GLsizei, height::GLsizei, xorig::GLfloat, yorig::GLfloat, xmove::GLfloat, ymove::GLfloat, bitmap::Ptr{GLubyte})::Void

export glreadpixels
@g glreadpixels glReadPixels(x::GLint, y::GLint, width::GLsizei, height::GLsizei, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export gldrawpixels
@g gldrawpixels glDrawPixels(width::GLsizei, height::GLsizei, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export glcopypixels
@g glcopypixels glCopyPixels(x::GLint, y::GLint, width::GLsizei, height::GLsizei, type::GLenum)::Void

export glstencilfunc
@g glstencilfunc glStencilFunc(func::GLenum, ref::GLint, mask::GLuint)::Void

export glstencilmask
@g glstencilmask glStencilMask(mask::GLuint)::Void

export glstencilop
@g glstencilop glStencilOp(fail::GLenum, zfail::GLenum, zpass::GLenum)::Void

export glclearstencil
@g glclearstencil glClearStencil(s::GLint)::Void

export gltexgend
@g gltexgend glTexGend(coord::GLenum, pname::GLenum, param::GLdouble)::Void

export gltexgenf
@g gltexgenf glTexGenf(coord::GLenum, pname::GLenum, param::GLfloat)::Void

export gltexgeni
@g gltexgeni glTexGeni(coord::GLenum, pname::GLenum, param::GLint)::Void

export gltexgendv
@g gltexgendv glTexGendv(coord::GLenum, pname::GLenum, params::Ptr{GLdouble})::Void

export gltexgenfv
@g gltexgenfv glTexGenfv(coord::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export gltexgeniv
@g gltexgeniv glTexGeniv(coord::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glgettexgendv
@g glgettexgendv glGetTexGendv(coord::GLenum, pname::GLenum, params::Ptr{GLdouble})::Void

export glgettexgenfv
@g glgettexgenfv glGetTexGenfv(coord::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgettexgeniv
@g glgettexgeniv glGetTexGeniv(coord::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export gltexenvf
@g gltexenvf glTexEnvf(target::GLenum, pname::GLenum, param::GLfloat)::Void

export gltexenvi
@g gltexenvi glTexEnvi(target::GLenum, pname::GLenum, param::GLint)::Void

export gltexenvfv
@g gltexenvfv glTexEnvfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export gltexenviv
@g gltexenviv glTexEnviv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glgettexenvfv
@g glgettexenvfv glGetTexEnvfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgettexenviv
@g glgettexenviv glGetTexEnviv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export gltexparameterf
@g gltexparameterf glTexParameterf(target::GLenum, pname::GLenum, param::GLfloat)::Void

export gltexparameteri
@g gltexparameteri glTexParameteri(target::GLenum, pname::GLenum, param::GLint)::Void

export gltexparameterfv
@g gltexparameterfv glTexParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export gltexparameteriv
@g gltexparameteriv glTexParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glgettexparameterfv
@g glgettexparameterfv glGetTexParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgettexparameteriv
@g glgettexparameteriv glGetTexParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glgettexlevelparameterfv
@g glgettexlevelparameterfv glGetTexLevelParameterfv(target::GLenum, level::GLint, pname::GLenum, params::Ptr{GLfloat})::Void

export glgettexlevelparameteriv
@g glgettexlevelparameteriv glGetTexLevelParameteriv(target::GLenum, level::GLint, pname::GLenum, params::Ptr{GLint})::Void

export glteximage1d
@g glteximage1d glTexImage1D(target::GLenum, level::GLint, internalFormat::GLint, width::GLsizei, border::GLint, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export glteximage2d
@g glteximage2d glTexImage2D(target::GLenum, level::GLint, internalFormat::GLint, width::GLsizei, height::GLsizei, border::GLint, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export glgetteximage
@g glgetteximage glGetTexImage(target::GLenum, level::GLint, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export glgentextures
@g glgentextures glGenTextures(n::GLsizei, textures::Ptr{GLuint})::Void

export gldeletetextures
@g gldeletetextures glDeleteTextures(n::GLsizei, textures::Ptr{GLuint})::Void

export glbindtexture
@g glbindtexture glBindTexture(target::GLenum, texture::GLuint)::Void

export glprioritizetextures
@g glprioritizetextures glPrioritizeTextures(n::GLsizei, textures::Ptr{GLuint}, priorities::Ptr{GLclampf})::Void

export glaretexturesresident
@g glaretexturesresident glAreTexturesResident(n::GLsizei, textures::Ptr{GLuint}, residences::Ptr{GLboolean})::GLboolean

export glistexture
@g glistexture glIsTexture(texture::GLuint)::GLboolean

export gltexsubimage1d
@g gltexsubimage1d glTexSubImage1D(target::GLenum, level::GLint, xoffset::GLint, width::GLsizei, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export gltexsubimage2d
@g gltexsubimage2d glTexSubImage2D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, width::GLsizei, height::GLsizei, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export glcopyteximage1d
@g glcopyteximage1d glCopyTexImage1D(target::GLenum, level::GLint, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei, border::GLint)::Void

export glcopyteximage2d
@g glcopyteximage2d glCopyTexImage2D(target::GLenum, level::GLint, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei, height::GLsizei, border::GLint)::Void

export glcopytexsubimage1d
@g glcopytexsubimage1d glCopyTexSubImage1D(target::GLenum, level::GLint, xoffset::GLint, x::GLint, y::GLint, width::GLsizei)::Void

export glcopytexsubimage2d
@g glcopytexsubimage2d glCopyTexSubImage2D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void

export glmap1d
@g glmap1d glMap1d(target::GLenum, u1::GLdouble, u2::GLdouble, stride::GLint, order::GLint, points::Ptr{GLdouble})::Void

export glmap1f
@g glmap1f glMap1f(target::GLenum, u1::GLfloat, u2::GLfloat, stride::GLint, order::GLint, points::Ptr{GLfloat})::Void

export glmap2d
@g glmap2d glMap2d(target::GLenum, u1::GLdouble, u2::GLdouble, ustride::GLint, uorder::GLint, v1::GLdouble, v2::GLdouble, vstride::GLint, vorder::GLint, points::Ptr{GLdouble})::Void

export glmap2f
@g glmap2f glMap2f(target::GLenum, u1::GLfloat, u2::GLfloat, ustride::GLint, uorder::GLint, v1::GLfloat, v2::GLfloat, vstride::GLint, vorder::GLint, points::Ptr{GLfloat})::Void

export glgetmapdv
@g glgetmapdv glGetMapdv(target::GLenum, query::GLenum, v::Ptr{GLdouble})::Void

export glgetmapfv
@g glgetmapfv glGetMapfv(target::GLenum, query::GLenum, v::Ptr{GLfloat})::Void

export glgetmapiv
@g glgetmapiv glGetMapiv(target::GLenum, query::GLenum, v::Ptr{GLint})::Void

export glevalcoord1d
@g glevalcoord1d glEvalCoord1d(u::GLdouble)::Void

export glevalcoord1f
@g glevalcoord1f glEvalCoord1f(u::GLfloat)::Void

export glevalcoord1dv
@g glevalcoord1dv glEvalCoord1dv(u::Ptr{GLdouble})::Void

export glevalcoord1fv
@g glevalcoord1fv glEvalCoord1fv(u::Ptr{GLfloat})::Void

export glevalcoord2d
@g glevalcoord2d glEvalCoord2d(u::GLdouble, v::GLdouble)::Void

export glevalcoord2f
@g glevalcoord2f glEvalCoord2f(u::GLfloat, v::GLfloat)::Void

export glevalcoord2dv
@g glevalcoord2dv glEvalCoord2dv(u::Ptr{GLdouble})::Void

export glevalcoord2fv
@g glevalcoord2fv glEvalCoord2fv(u::Ptr{GLfloat})::Void

export glmapgrid1d
@g glmapgrid1d glMapGrid1d(un::GLint, u1::GLdouble, u2::GLdouble)::Void

export glmapgrid1f
@g glmapgrid1f glMapGrid1f(un::GLint, u1::GLfloat, u2::GLfloat)::Void

export glmapgrid2d
@g glmapgrid2d glMapGrid2d(un::GLint, u1::GLdouble, u2::GLdouble, vn::GLint, v1::GLdouble, v2::GLdouble)::Void

export glmapgrid2f
@g glmapgrid2f glMapGrid2f(un::GLint, u1::GLfloat, u2::GLfloat, vn::GLint, v1::GLfloat, v2::GLfloat)::Void

export glevalpoint1
@g glevalpoint1 glEvalPoint1(i::GLint)::Void

export glevalpoint2
@g glevalpoint2 glEvalPoint2(i::GLint, j::GLint)::Void

export glevalmesh1
@g glevalmesh1 glEvalMesh1(mode::GLenum, i1::GLint, i2::GLint)::Void

export glevalmesh2
@g glevalmesh2 glEvalMesh2(mode::GLenum, i1::GLint, i2::GLint, j1::GLint, j2::GLint)::Void

export glfogf
@g glfogf glFogf(pname::GLenum, param::GLfloat)::Void

export glfogi
@g glfogi glFogi(pname::GLenum, param::GLint)::Void

export glfogfv
@g glfogfv glFogfv(pname::GLenum, params::Ptr{GLfloat})::Void

export glfogiv
@g glfogiv glFogiv(pname::GLenum, params::Ptr{GLint})::Void

export glfeedbackbuffer
@g glfeedbackbuffer glFeedbackBuffer(size::GLsizei, type::GLenum, buffer::Ptr{GLfloat})::Void

export glpassthrough
@g glpassthrough glPassThrough(token::GLfloat)::Void

export glselectbuffer
@g glselectbuffer glSelectBuffer(size::GLsizei, buffer::Ptr{GLuint})::Void

export glinitnames
@g glinitnames glInitNames()::Void

export glloadname
@g glloadname glLoadName(name::GLuint)::Void

export glpushname
@g glpushname glPushName(name::GLuint)::Void

export glpopname
@g glpopname glPopName()::Void

export gldrawrangeelements
@g gldrawrangeelements glDrawRangeElements(mode::GLenum, start::GLuint, end::GLuint, count::GLsizei, type::GLenum, indices::Ptr{GLvoid})::Void

export glteximage3d
@g glteximage3d glTexImage3D(target::GLenum, level::GLint, internalFormat::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, border::GLint, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export gltexsubimage3d
@g gltexsubimage3d glTexSubImage3D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, zoffset::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, format::GLenum, type::GLenum, pixels::Ptr{GLvoid})::Void

export glcopytexsubimage3d
@g glcopytexsubimage3d glCopyTexSubImage3D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, zoffset::GLint, x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void

export glcolortable
@g glcolortable glColorTable(target::GLenum, internalformat::GLenum, width::GLsizei, format::GLenum, type::GLenum, table::Ptr{GLvoid})::Void

export glcolorsubtable
@g glcolorsubtable glColorSubTable(target::GLenum, start::GLsizei, count::GLsizei, format::GLenum, type::GLenum, data::Ptr{GLvoid})::Void

export glcolortableparameteriv
@g glcolortableparameteriv glColorTableParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glcolortableparameterfv
@g glcolortableparameterfv glColorTableParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glcopycolorsubtable
@g glcopycolorsubtable glCopyColorSubTable(target::GLenum, start::GLsizei, x::GLint, y::GLint, width::GLsizei)::Void

export glcopycolortable
@g glcopycolortable glCopyColorTable(target::GLenum, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei)::Void

export glgetcolortable
@g glgetcolortable glGetColorTable(target::GLenum, format::GLenum, type::GLenum, table::Ptr{GLvoid})::Void

export glgetcolortableparameterfv
@g glgetcolortableparameterfv glGetColorTableParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgetcolortableparameteriv
@g glgetcolortableparameteriv glGetColorTableParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glblendequation
@g glblendequation glBlendEquation(mode::GLenum)::Void

export glblendcolor
@g glblendcolor glBlendColor(red::GLclampf, green::GLclampf, blue::GLclampf, alpha::GLclampf)::Void

export glhistogram
@g glhistogram glHistogram(target::GLenum, width::GLsizei, internalformat::GLenum, sink::GLboolean)::Void

export glresethistogram
@g glresethistogram glResetHistogram(target::GLenum)::Void

export glgethistogram
@g glgethistogram glGetHistogram(target::GLenum, reset::GLboolean, format::GLenum, type::GLenum, values::Ptr{GLvoid})::Void

export glgethistogramparameterfv
@g glgethistogramparameterfv glGetHistogramParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgethistogramparameteriv
@g glgethistogramparameteriv glGetHistogramParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glminmax
@g glminmax glMinmax(target::GLenum, internalformat::GLenum, sink::GLboolean)::Void

export glresetminmax
@g glresetminmax glResetMinmax(target::GLenum)::Void

export glgetminmax
@g glgetminmax glGetMinmax(target::GLenum, reset::GLboolean, format::GLenum, types::GLenum, values::Ptr{GLvoid})::Void

export glgetminmaxparameterfv
@g glgetminmaxparameterfv glGetMinmaxParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgetminmaxparameteriv
@g glgetminmaxparameteriv glGetMinmaxParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glconvolutionfilter1d
@g glconvolutionfilter1d glConvolutionFilter1D(target::GLenum, internalformat::GLenum, width::GLsizei, format::GLenum, type::GLenum, image::Ptr{GLvoid})::Void

export glconvolutionfilter2d
@g glconvolutionfilter2d glConvolutionFilter2D(target::GLenum, internalformat::GLenum, width::GLsizei, height::GLsizei, format::GLenum, type::GLenum, image::Ptr{GLvoid})::Void

export glconvolutionparameterf
@g glconvolutionparameterf glConvolutionParameterf(target::GLenum, pname::GLenum, params::GLfloat)::Void

export glconvolutionparameterfv
@g glconvolutionparameterfv glConvolutionParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glconvolutionparameteri
@g glconvolutionparameteri glConvolutionParameteri(target::GLenum, pname::GLenum, params::GLint)::Void

export glconvolutionparameteriv
@g glconvolutionparameteriv glConvolutionParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glcopyconvolutionfilter1d
@g glcopyconvolutionfilter1d glCopyConvolutionFilter1D(target::GLenum, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei)::Void

export glcopyconvolutionfilter2d
@g glcopyconvolutionfilter2d glCopyConvolutionFilter2D(target::GLenum, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void

export glgetconvolutionfilter
@g glgetconvolutionfilter glGetConvolutionFilter(target::GLenum, format::GLenum, type::GLenum, image::Ptr{GLvoid})::Void

export glgetconvolutionparameterfv
@g glgetconvolutionparameterfv glGetConvolutionParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void

export glgetconvolutionparameteriv
@g glgetconvolutionparameteriv glGetConvolutionParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void

export glseparablefilter2d
@g glseparablefilter2d glSeparableFilter2D(target::GLenum, internalformat::GLenum, width::GLsizei, height::GLsizei, format::GLenum, type::GLenum, row::Ptr{GLvoid}, column::Ptr{GLvoid})::Void

export glgetseparablefilter
@g glgetseparablefilter glGetSeparableFilter(target::GLenum, format::GLenum, type::GLenum, row::Ptr{GLvoid}, column::Ptr{GLvoid}, span::Ptr{GLvoid})::Void

export glactivetexture
@g glactivetexture glActiveTexture(texture::GLenum)::Void

export glclientactivetexture
@g glclientactivetexture glClientActiveTexture(texture::GLenum)::Void

export glcompressedteximage1d
@g glcompressedteximage1d glCompressedTexImage1D(target::GLenum, level::GLint, internalformat::GLenum, width::GLsizei, border::GLint, imageSize::GLsizei, data::Ptr{GLvoid})::Void

export glcompressedteximage2d
@g glcompressedteximage2d glCompressedTexImage2D(target::GLenum, level::GLint, internalformat::GLenum, width::GLsizei, height::GLsizei, border::GLint, imageSize::GLsizei, data::Ptr{GLvoid})::Void

export glcompressedteximage3d
@g glcompressedteximage3d glCompressedTexImage3D(target::GLenum, level::GLint, internalformat::GLenum, width::GLsizei, height::GLsizei, depth::GLsizei, border::GLint, imageSize::GLsizei, data::Ptr{GLvoid})::Void

export glcompressedtexsubimage1d
@g glcompressedtexsubimage1d glCompressedTexSubImage1D(target::GLenum, level::GLint, xoffset::GLint, width::GLsizei, format::GLenum, imageSize::GLsizei, data::Ptr{GLvoid})::Void

export glcompressedtexsubimage2d
@g glcompressedtexsubimage2d glCompressedTexSubImage2D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, width::GLsizei, height::GLsizei, format::GLenum, imageSize::GLsizei, data::Ptr{GLvoid})::Void

export glcompressedtexsubimage3d
@g glcompressedtexsubimage3d glCompressedTexSubImage3D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, zoffset::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, format::GLenum, imageSize::GLsizei, data::Ptr{GLvoid})::Void

export glgetcompressedteximage
@g glgetcompressedteximage glGetCompressedTexImage(target::GLenum, lod::GLint, img::Ptr{GLvoid})::Void

export glmultitexcoord1d
@g glmultitexcoord1d glMultiTexCoord1d(target::GLenum, s::GLdouble)::Void

export glmultitexcoord1dv
@g glmultitexcoord1dv glMultiTexCoord1dv(target::GLenum, v::Ptr{GLdouble})::Void

export glmultitexcoord1f
@g glmultitexcoord1f glMultiTexCoord1f(target::GLenum, s::GLfloat)::Void

export glmultitexcoord1fv
@g glmultitexcoord1fv glMultiTexCoord1fv(target::GLenum, v::Ptr{GLfloat})::Void

export glmultitexcoord1i
@g glmultitexcoord1i glMultiTexCoord1i(target::GLenum, s::GLint)::Void

export glmultitexcoord1iv
@g glmultitexcoord1iv glMultiTexCoord1iv(target::GLenum, v::Ptr{GLint})::Void

export glmultitexcoord1s
@g glmultitexcoord1s glMultiTexCoord1s(target::GLenum, s::GLshort)::Void

export glmultitexcoord1sv
@g glmultitexcoord1sv glMultiTexCoord1sv(target::GLenum, v::Ptr{GLshort})::Void

export glmultitexcoord2d
@g glmultitexcoord2d glMultiTexCoord2d(target::GLenum, s::GLdouble, t::GLdouble)::Void

export glmultitexcoord2dv
@g glmultitexcoord2dv glMultiTexCoord2dv(target::GLenum, v::Ptr{GLdouble})::Void

export glmultitexcoord2f
@g glmultitexcoord2f glMultiTexCoord2f(target::GLenum, s::GLfloat, t::GLfloat)::Void

export glmultitexcoord2fv
@g glmultitexcoord2fv glMultiTexCoord2fv(target::GLenum, v::Ptr{GLfloat})::Void

export glmultitexcoord2i
@g glmultitexcoord2i glMultiTexCoord2i(target::GLenum, s::GLint, t::GLint)::Void

export glmultitexcoord2iv
@g glmultitexcoord2iv glMultiTexCoord2iv(target::GLenum, v::Ptr{GLint})::Void

export glmultitexcoord2s
@g glmultitexcoord2s glMultiTexCoord2s(target::GLenum, s::GLshort, t::GLshort)::Void

export glmultitexcoord2sv
@g glmultitexcoord2sv glMultiTexCoord2sv(target::GLenum, v::Ptr{GLshort})::Void

export glmultitexcoord3d
@g glmultitexcoord3d glMultiTexCoord3d(target::GLenum, s::GLdouble, t::GLdouble, r::GLdouble)::Void

export glmultitexcoord3dv
@g glmultitexcoord3dv glMultiTexCoord3dv(target::GLenum, v::Ptr{GLdouble})::Void

export glmultitexcoord3f
@g glmultitexcoord3f glMultiTexCoord3f(target::GLenum, s::GLfloat, t::GLfloat, r::GLfloat)::Void

export glmultitexcoord3fv
@g glmultitexcoord3fv glMultiTexCoord3fv(target::GLenum, v::Ptr{GLfloat})::Void

export glmultitexcoord3i
@g glmultitexcoord3i glMultiTexCoord3i(target::GLenum, s::GLint, t::GLint, r::GLint)::Void

export glmultitexcoord3iv
@g glmultitexcoord3iv glMultiTexCoord3iv(target::GLenum, v::Ptr{GLint})::Void

export glmultitexcoord3s
@g glmultitexcoord3s glMultiTexCoord3s(target::GLenum, s::GLshort, t::GLshort, r::GLshort)::Void

export glmultitexcoord3sv
@g glmultitexcoord3sv glMultiTexCoord3sv(target::GLenum, v::Ptr{GLshort})::Void

export glmultitexcoord4d
@g glmultitexcoord4d glMultiTexCoord4d(target::GLenum, s::GLdouble, t::GLdouble, r::GLdouble, q::GLdouble)::Void

export glmultitexcoord4dv
@g glmultitexcoord4dv glMultiTexCoord4dv(target::GLenum, v::Ptr{GLdouble})::Void

export glmultitexcoord4f
@g glmultitexcoord4f glMultiTexCoord4f(target::GLenum, s::GLfloat, t::GLfloat, r::GLfloat, q::GLfloat)::Void

export glmultitexcoord4fv
@g glmultitexcoord4fv glMultiTexCoord4fv(target::GLenum, v::Ptr{GLfloat})::Void

export glmultitexcoord4i
@g glmultitexcoord4i glMultiTexCoord4i(target::GLenum, s::GLint, t::GLint, r::GLint, q::GLint)::Void

export glmultitexcoord4iv
@g glmultitexcoord4iv glMultiTexCoord4iv(target::GLenum, v::Ptr{GLint})::Void

export glmultitexcoord4s
@g glmultitexcoord4s glMultiTexCoord4s(target::GLenum, s::GLshort, t::GLshort, r::GLshort, q::GLshort)::Void

export glmultitexcoord4sv
@g glmultitexcoord4sv glMultiTexCoord4sv(target::GLenum, v::Ptr{GLshort})::Void

export glloadtransposematrixd
@g glloadtransposematrixd glLoadTransposeMatrixd(m::Ptr{GLdouble})::Void

export glloadtransposematrixf
@g glloadtransposematrixf glLoadTransposeMatrixf(m::Ptr{GLfloat})::Void

export glmulttransposematrixd
@g glmulttransposematrixd glMultTransposeMatrixd(m::Ptr{GLdouble})::Void

export glmulttransposematrixf
@g glmulttransposematrixf glMultTransposeMatrixf(m::Ptr{GLfloat})::Void

export glsamplecoverage
@g glsamplecoverage glSampleCoverage(value::GLclampf, invert::GLboolean)::Void

export glactivetexturearb
@g glactivetexturearb glActiveTextureARB(texture::GLenum)::Void

export glclientactivetexturearb
@g glclientactivetexturearb glClientActiveTextureARB(texture::GLenum)::Void

export glmultitexcoord1darb
@g glmultitexcoord1darb glMultiTexCoord1dARB(target::GLenum, s::GLdouble)::Void

export glmultitexcoord1dvarb
@g glmultitexcoord1dvarb glMultiTexCoord1dvARB(target::GLenum, v::Ptr{GLdouble})::Void

export glmultitexcoord1farb
@g glmultitexcoord1farb glMultiTexCoord1fARB(target::GLenum, s::GLfloat)::Void

export glmultitexcoord1fvarb
@g glmultitexcoord1fvarb glMultiTexCoord1fvARB(target::GLenum, v::Ptr{GLfloat})::Void

export glmultitexcoord1iarb
@g glmultitexcoord1iarb glMultiTexCoord1iARB(target::GLenum, s::GLint)::Void

export glmultitexcoord1ivarb
@g glmultitexcoord1ivarb glMultiTexCoord1ivARB(target::GLenum, v::Ptr{GLint})::Void

export glmultitexcoord1sarb
@g glmultitexcoord1sarb glMultiTexCoord1sARB(target::GLenum, s::GLshort)::Void

export glmultitexcoord1svarb
@g glmultitexcoord1svarb glMultiTexCoord1svARB(target::GLenum, v::Ptr{GLshort})::Void

export glmultitexcoord2darb
@g glmultitexcoord2darb glMultiTexCoord2dARB(target::GLenum, s::GLdouble, t::GLdouble)::Void

export glmultitexcoord2dvarb
@g glmultitexcoord2dvarb glMultiTexCoord2dvARB(target::GLenum, v::Ptr{GLdouble})::Void

export glmultitexcoord2farb
@g glmultitexcoord2farb glMultiTexCoord2fARB(target::GLenum, s::GLfloat, t::GLfloat)::Void

export glmultitexcoord2fvarb
@g glmultitexcoord2fvarb glMultiTexCoord2fvARB(target::GLenum, v::Ptr{GLfloat})::Void

export glmultitexcoord2iarb
@g glmultitexcoord2iarb glMultiTexCoord2iARB(target::GLenum, s::GLint, t::GLint)::Void

export glmultitexcoord2ivarb
@g glmultitexcoord2ivarb glMultiTexCoord2ivARB(target::GLenum, v::Ptr{GLint})::Void

export glmultitexcoord2sarb
@g glmultitexcoord2sarb glMultiTexCoord2sARB(target::GLenum, s::GLshort, t::GLshort)::Void

export glmultitexcoord2svarb
@g glmultitexcoord2svarb glMultiTexCoord2svARB(target::GLenum, v::Ptr{GLshort})::Void

export glmultitexcoord3darb
@g glmultitexcoord3darb glMultiTexCoord3dARB(target::GLenum, s::GLdouble, t::GLdouble, r::GLdouble)::Void

export glmultitexcoord3dvarb
@g glmultitexcoord3dvarb glMultiTexCoord3dvARB(target::GLenum, v::Ptr{GLdouble})::Void

export glmultitexcoord3farb
@g glmultitexcoord3farb glMultiTexCoord3fARB(target::GLenum, s::GLfloat, t::GLfloat, r::GLfloat)::Void

export glmultitexcoord3fvarb
@g glmultitexcoord3fvarb glMultiTexCoord3fvARB(target::GLenum, v::Ptr{GLfloat})::Void

export glmultitexcoord3iarb
@g glmultitexcoord3iarb glMultiTexCoord3iARB(target::GLenum, s::GLint, t::GLint, r::GLint)::Void

export glmultitexcoord3ivarb
@g glmultitexcoord3ivarb glMultiTexCoord3ivARB(target::GLenum, v::Ptr{GLint})::Void

export glmultitexcoord3sarb
@g glmultitexcoord3sarb glMultiTexCoord3sARB(target::GLenum, s::GLshort, t::GLshort, r::GLshort)::Void

export glmultitexcoord3svarb
@g glmultitexcoord3svarb glMultiTexCoord3svARB(target::GLenum, v::Ptr{GLshort})::Void

export glmultitexcoord4darb
@g glmultitexcoord4darb glMultiTexCoord4dARB(target::GLenum, s::GLdouble, t::GLdouble, r::GLdouble, q::GLdouble)::Void

export glmultitexcoord4dvarb
@g glmultitexcoord4dvarb glMultiTexCoord4dvARB(target::GLenum, v::Ptr{GLdouble})::Void

export glmultitexcoord4farb
@g glmultitexcoord4farb glMultiTexCoord4fARB(target::GLenum, s::GLfloat, t::GLfloat, r::GLfloat, q::GLfloat)::Void

export glmultitexcoord4fvarb
@g glmultitexcoord4fvarb glMultiTexCoord4fvARB(target::GLenum, v::Ptr{GLfloat})::Void

export glmultitexcoord4iarb
@g glmultitexcoord4iarb glMultiTexCoord4iARB(target::GLenum, s::GLint, t::GLint, r::GLint, q::GLint)::Void

export glmultitexcoord4ivarb
@g glmultitexcoord4ivarb glMultiTexCoord4ivARB(target::GLenum, v::Ptr{GLint})::Void

export glmultitexcoord4sarb
@g glmultitexcoord4sarb glMultiTexCoord4sARB(target::GLenum, s::GLshort, t::GLshort, r::GLshort, q::GLshort)::Void

export glmultitexcoord4svarb
@g glmultitexcoord4svarb glMultiTexCoord4svARB(target::GLenum, v::Ptr{GLshort})::Void

export glcreatedebugobjectmesa
@g glcreatedebugobjectmesa glCreateDebugObjectMESA()::GLhandleARB

export glcleardebuglogmesa
@g glcleardebuglogmesa glClearDebugLogMESA(obj::GLhandleARB, logType::GLenum, shaderType::GLenum)::Void

export glgetdebuglogmesa
@g glgetdebuglogmesa glGetDebugLogMESA(obj::GLhandleARB, logType::GLenum, shaderType::GLenum, maxLength::GLsizei, length::Ptr{GLsizei}, debugLog::Ptr{GLcharARB})::Void

export glgetdebugloglengthmesa
@g glgetdebugloglengthmesa glGetDebugLogLengthMESA(obj::GLhandleARB, logType::GLenum, shaderType::GLenum)::GLsizei

export GLprogramcallbackMESA
typealias GLprogramcallbackMESA FunPtr{{:GLenum, :( Ptr{GLvoid} )}, Void, 1}

export glprogramcallbackmesa
@g glprogramcallbackmesa glProgramCallbackMESA(target::GLenum, callback::GLprogramcallbackMESA, data::Ptr{GLvoid})::Void

export glgetprogramregisterfvmesa
@g glgetprogramregisterfvmesa glGetProgramRegisterfvMESA(target::GLenum, len::GLsizei, name::Ptr{GLubyte}, v::Ptr{GLfloat})::Void

export glblendequationseparateati
@g glblendequationseparateati glBlendEquationSeparateATI(modeRGB::GLenum, modeA::GLenum)::Void

export GLeglImageOES
typealias GLeglImageOES Ptr{Void}


end #module Gl
