#Autogenerated, parameters: 

module Stdc-predef

#Autogenerated module of /usr/include/stdc-predef.h
module Stdc-predef
using Base, GetC

#Load library.

lib=dlopen("libstdc-predef")
macro g(name, c_fun) #Makes stuff shorter.
    :(@get_c_fun lib $name $c_fun)
end

#AutoFFI body.


end #module Stdc-predef
