# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

sum = 0
(x, y) = (1, 2)
while x < 4e6
  if x % 2 == 0
    sum += x
  end
  (x, y) = (y, x + y)
end

println(sum)
# 4613732
